export const copy = {
  title: 'World Snap',
  subtitle: 'Собери мир из стран',
  toTable: 'К столу',
  choose: 'Выбери страну.',
  chooseHint: 'Три силуэта. Глобус ещё белый.',
  paint: 'Флаг — по желанию.',
  place: 'Теперь на глобус.',
  contour: 'Поставь на контур.',
  hint: 'Положи страну на её место',
  miss: 'Не та широта',
  missHint: 'Ближе к контуру.',
  snap: 'Есть.',
  scatter: 'Остальные — на стол.',
  complete: 'Мир собран',
  completeHint: 'Восемь стран на месте.',
  collection: 'Коллекция',
  toCollection: 'В коллекцию',
  replay: 'Ещё раз',
  locked: 'Скоро',
  pack: 'Восемь стран',
  europe: 'Европа',
  continents: 'Континенты',
  states: 'Штаты и провинции',
  resume: 'Продолжить сборку?',
  continue: 'Продолжить',
  startOver: 'Сначала',
  loading: 'Собираем стол…',
  error: 'Не загрузилось.',
  count: (n: number, total: number) => `${n} из ${total}`,
} as const
